# Generated by Django 5.1.1 on 2024-09-06 10:51

import django.db.models.deletion
import forms.models
import wagtail.contrib.forms.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('to_address', models.CharField(blank=True, help_text='Optional - form submissions will be emailed to these addresses. Separate multiple addresses by comma.', max_length=255, validators=[wagtail.contrib.forms.models.validate_to_address], verbose_name='to address')),
                ('from_address', models.EmailField(blank=True, max_length=255, verbose_name='from address')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='subject')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('form_fields', wagtail.fields.StreamField([('singleline', 6), ('multiline', 10), ('email', 12), ('number', 16), ('url', 18), ('checkbox', 20), ('checkboxes', 25), ('dropdown', 29), ('multiselect', 29), ('radio', 29), ('date', 31), ('datetime', 33), ('hidden', 34)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Text describing the field.'}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Text displayed below the label used to add more information, like this one.', 'required': False}), 2: ('wagtail.blocks.BooleanBlock', (), {'help_text': 'If checked, this field must be filled to validate the form.', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Text used to pre-fill the field.', 'label': 'Default value', 'required': False}), 4: ('wagtail.blocks.IntegerBlock', (), {'default': 0, 'help_text': 'Minimum amount of characters allowed in the field.'}), 5: ('wagtail.blocks.IntegerBlock', (), {'default': 255, 'help_text': 'Maximum amount of characters allowed in the field.'}), 6: ('wagtail.blocks.StructBlock', [[('label', 0), ('help_text', 1), ('required', 2), ('initial', 3), ('min_length', 4), ('max_length', 5)]], {}), 7: ('wagtail.blocks.TextBlock', (), {'help_text': 'Multi-line text used to pre-fill the text area.', 'label': 'Default value', 'required': False}), 8: ('wagtail.blocks.IntegerBlock', (), {'default': 0, 'help_text': 'Minimum amount of characters allowed in the text area.'}), 9: ('wagtail.blocks.IntegerBlock', (), {'default': 1024, 'help_text': 'Maximum amount of characters allowed in the text area.'}), 10: ('wagtail.blocks.StructBlock', [[('label', 0), ('help_text', 1), ('required', 2), ('initial', 7), ('min_length', 8), ('max_length', 9)]], {}), 11: ('wagtail.blocks.EmailBlock', (), {'help_text': 'E-mail used to pre-fill the field.', 'label': 'Default value', 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('label', 0), ('help_text', 1), ('required', 2), ('initial', 11)]], {}), 13: ('wagtail.blocks.DecimalBlock', (), {'help_text': 'Number used to pre-fill the field.', 'label': 'Default value', 'required': False}), 14: ('wagtail.blocks.IntegerBlock', (), {'help_text': 'Minimum number allowed in the field.', 'required': False}), 15: ('wagtail.blocks.IntegerBlock', (), {'help_text': 'Maximum number allowed in the field.', 'required': False}), 16: ('wagtail.blocks.StructBlock', [[('label', 0), ('help_text', 1), ('required', 2), ('initial', 13), ('min_value', 14), ('max_value', 15)]], {}), 17: ('wagtail.blocks.URLBlock', (), {'help_text': 'URL used to pre-fill the field.', 'label': 'Default value', 'required': False}), 18: ('wagtail.blocks.StructBlock', [[('label', 0), ('help_text', 1), ('required', 2), ('initial', 17)]], {}), 19: ('wagtail.blocks.BooleanBlock', (), {'help_text': 'If checked, the checkbox will be checked by default.', 'label': 'Checked', 'required': False}), 20: ('wagtail.blocks.StructBlock', [[('label', 0), ('help_text', 1), ('required', 2), ('initial', 19)]], {}), 21: ('wagtail.blocks.CharBlock', (), {'label': 'Label'}), 22: ('wagtail.blocks.BooleanBlock', (), {'label': 'Checked', 'required': False}), 23: ('wagtail.blocks.StructBlock', [[('label', 21), ('initial', 22)]], {}), 24: ('wagtail.blocks.ListBlock', (23,), {'label': 'Choices'}), 25: ('wagtail.blocks.StructBlock', [[('label', 0), ('help_text', 1), ('required', 2), ('choices', 24)]], {}), 26: ('wagtail.blocks.BooleanBlock', (), {'label': 'Selected', 'required': False}), 27: ('wagtail.blocks.StructBlock', [[('label', 21), ('initial', 26)]], {}), 28: ('wagtail.blocks.ListBlock', (27,), {'label': 'Choices'}), 29: ('wagtail.blocks.StructBlock', [[('label', 0), ('help_text', 1), ('required', 2), ('choices', 28)]], {}), 30: ('wagtail.blocks.DateBlock', (), {'help_text': 'Date used to pre-fill the field.', 'label': 'Default value', 'required': False}), 31: ('wagtail.blocks.StructBlock', [[('label', 0), ('help_text', 1), ('required', 2), ('initial', 30)]], {}), 32: ('wagtail.blocks.DateTimeBlock', (), {'help_text': 'Date/time used to pre-fill the field.', 'label': 'Default value', 'required': False}), 33: ('wagtail.blocks.StructBlock', [[('label', 0), ('help_text', 1), ('required', 2), ('initial', 32)]], {}), 34: ('wagtail.blocks.StructBlock', [[('label', 0), ('help_text', 1), ('required', 2), ('initial', 3)]], {})})),
                ('thank_you_text', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(forms.models.StreamFieldFormMixin, 'wagtailcore.page', models.Model),
        ),
    ]
