# Generated by Django 5.2.7 on 2025-10-22 12:00

import django.core.serializers.json
import django.db.models.deletion
import modelcluster.fields
import wagtail.contrib.forms.models
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, default='Forms list', help_text='A rich text introduction to be displayed before the list of forms.', verbose_name='Form index page introduction')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='CustomFormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_data', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('submit_time', models.DateTimeField(auto_now_add=True, verbose_name='submit time')),
                ('index', models.IntegerField(default=0)),
                ('email', models.EmailField(default='', max_length=254)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.page')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FormPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('unique_response', models.BooleanField(default=False, help_text='If checked, the user may fill in the form only once.', verbose_name='Unique response')),
                ('validation_title', models.CharField(default='User validation required to fill a public form', max_length=100, verbose_name='E-mail title')),
                ('validation_body', wagtail.fields.RichTextField(default='Please click on the following link to fill the form: {validation_url} .', verbose_name='E-mail content')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='Form introduction text')),
                ('form_fields', wagtail.fields.StreamField([('singleline', 8), ('multiline', 11), ('email', 13), ('number', 17), ('url', 19), ('checkbox', 22), ('checkboxes', 25), ('dropdown', 27), ('multiselect', 29), ('radio', 27), ('date', 31), ('time', 33), ('datetime', 35), ('hidden', 37), ('label', 40), ('file', 42)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'formbuilder-field-block-label', 'help_text': 'Short text describing the field.', 'label': 'Label'}), 1: ('wagtail_form_plugins.streamfield.blocks.SlugBlock', (), {'help_text': 'Identifier used to identify this field, for instance in conditional fields.', 'label': 'Slug', 'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Text displayed below the label to add more information.', 'label': 'Help text', 'required': False}), 3: ('wagtail_form_plugins.streamfield.blocks.RequiredBlock', (), {}), 4: ('wagtail.blocks.BooleanBlock', (), {'help_text': 'Check to make the field not editable by the user.', 'label': 'Disabled', 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Texte simple used to pre-fill the field.', 'label': 'Default value', 'required': False}), 6: ('wagtail.blocks.IntegerBlock', (), {'default': 0, 'help_text': 'Minimum amount of characters allowed in the field.', 'label': 'Min length'}), 7: ('wagtail.blocks.IntegerBlock', (), {'default': 255, 'help_text': 'Maximum amount of characters allowed in the field.', 'label': 'Max length'}), 8: ('wagtail.blocks.StructBlock', [[('label', 0), ('slug', 1), ('help_text', 2), ('is_required', 3), ('disabled', 4), ('initial', 5), ('min_length', 6), ('max_length', 7)]], {}), 9: ('wagtail.blocks.TextBlock', (), {'help_text': 'Texte multi-ligne used to pre-fill the field.', 'label': 'Default value', 'required': False}), 10: ('wagtail.blocks.IntegerBlock', (), {'default': 1024, 'help_text': 'Maximum amount of characters allowed in the field.', 'label': 'Max length'}), 11: ('wagtail.blocks.StructBlock', [[('label', 0), ('slug', 1), ('help_text', 2), ('is_required', 3), ('disabled', 4), ('initial', 9), ('min_length', 6), ('max_length', 10)]], {}), 12: ('wagtail.blocks.EmailBlock', (), {'help_text': 'E-mail used to pre-fill the field.', 'label': 'Default value', 'required': False}), 13: ('wagtail.blocks.StructBlock', [[('label', 0), ('slug', 1), ('help_text', 2), ('is_required', 3), ('disabled', 4), ('initial', 12)]], {}), 14: ('wagtail.blocks.DecimalBlock', (), {'help_text': 'Nombre used to pre-fill the field.', 'label': 'Default value', 'required': False}), 15: ('wagtail.blocks.IntegerBlock', (), {'help_text': 'Minimum number allowed in the field.', 'label': 'Min value', 'required': False}), 16: ('wagtail.blocks.IntegerBlock', (), {'help_text': 'Maximum number allowed in the field.', 'label': 'Max value', 'required': False}), 17: ('wagtail.blocks.StructBlock', [[('label', 0), ('slug', 1), ('help_text', 2), ('is_required', 3), ('disabled', 4), ('initial', 14), ('min_value', 15), ('max_value', 16)]], {}), 18: ('wagtail.blocks.URLBlock', (), {'help_text': 'URL used to pre-fill the field.', 'label': 'Default value', 'required': False}), 19: ('wagtail.blocks.StructBlock', [[('label', 0), ('slug', 1), ('help_text', 2), ('is_required', 3), ('disabled', 4), ('initial', 18)]], {}), 20: ('wagtail_form_plugins.streamfield.blocks.RequiredBlock', ('the box must be checked',), {}), 21: ('wagtail.blocks.BooleanBlock', (), {'help_text': 'If checked, the box will be checked by default.', 'label': 'Checked', 'required': False}), 22: ('wagtail.blocks.StructBlock', [[('label', 0), ('slug', 1), ('help_text', 2), ('is_required', 20), ('disabled', 4), ('initial', 21)]], {}), 23: ('wagtail_form_plugins.streamfield.blocks.RequiredBlock', ('at least one box must be checked',), {}), 24: ('wagtail.blocks.TextBlock', (), {'label': 'Choices list, one per line'}), 25: ('wagtail.blocks.StructBlock', [[('label', 0), ('slug', 1), ('help_text', 2), ('is_required', 23), ('disabled', 4), ('choices', 24)]], {}), 26: ('wagtail_form_plugins.streamfield.blocks.RequiredBlock', ('an item must be selected',), {}), 27: ('wagtail.blocks.StructBlock', [[('label', 0), ('slug', 1), ('help_text', 2), ('is_required', 26), ('disabled', 4), ('choices', 24)]], {}), 28: ('wagtail_form_plugins.streamfield.blocks.RequiredBlock', ('at least one item must be selected',), {}), 29: ('wagtail.blocks.StructBlock', [[('label', 0), ('slug', 1), ('help_text', 2), ('is_required', 28), ('disabled', 4), ('choices', 24)]], {}), 30: ('wagtail.blocks.DateBlock', (), {'help_text': 'Date used to pre-fill the field.', 'label': 'Default value', 'required': False}), 31: ('wagtail.blocks.StructBlock', [[('label', 0), ('slug', 1), ('help_text', 2), ('is_required', 3), ('disabled', 4), ('initial', 30)]], {}), 32: ('wagtail.blocks.TimeBlock', (), {'help_text': 'Heure used to pre-fill the field.', 'label': 'Default value', 'required': False}), 33: ('wagtail.blocks.StructBlock', [[('label', 0), ('slug', 1), ('help_text', 2), ('is_required', 3), ('disabled', 4), ('initial', 32)]], {}), 34: ('wagtail.blocks.DateTimeBlock', (), {'help_text': 'Date et heure used to pre-fill the field.', 'label': 'Default value', 'required': False}), 35: ('wagtail.blocks.StructBlock', [[('label', 0), ('slug', 1), ('help_text', 2), ('is_required', 3), ('disabled', 4), ('initial', 34)]], {}), 36: ('wagtail.blocks.CharBlock', (), {'help_text': 'Texte caché used to pre-fill the field.', 'label': 'Default value', 'required': False}), 37: ('wagtail.blocks.StructBlock', [[('label', 0), ('slug', 1), ('help_text', 2), ('is_required', 3), ('disabled', 4), ('initial', 36)]], {}), 38: ('wagtail.blocks.CharBlock', (), {'form_classname': 'formbuilder-field-block-label', 'label': 'Title'}), 39: ('wagtail.blocks.CharBlock', (), {'label': 'Sub-title', 'required': False}), 40: ('wagtail.blocks.StructBlock', [[('label', 38), ('help_text', 39)]], {}), 41: ('wagtail.blocks.MultipleChoiceBlock', [], {'choices': [('pdf', 'pdf'), ('jpg', 'jpg'), ('jpeg', 'jpeg'), ('png', 'png')], 'label': 'Allowed file extensions'}), 42: ('wagtail.blocks.StructBlock', [[('label', 0), ('slug', 1), ('help_text', 2), ('is_required', 3), ('disabled', 4), ('allowed_extensions', 41)]], {})}, verbose_name='Form fields')),
                ('thank_you_text', wagtail.fields.RichTextField(blank=True, default='Thank you!', verbose_name='Text displayed after form submission')),
                ('emails_to_send', wagtail.fields.StreamField([('email_to_send', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'E-mail addresses of the recipients, separated by comma.', 'label': 'Recipient list'}), 1: ('wagtail.blocks.CharBlock', (), {'default': 'contact@example.com', 'help_text': 'E-mail addresses set in the “from” email field, separated by comma.', 'label': 'From', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'E-mail addresses set in the “reply_to” email field, separated by comma.', 'label': 'Reply to', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'The subject of the e-mail.', 'label': 'Subject'}), 4: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'The body of the e-mail.', 'label': 'Message'}), 5: ('wagtail.blocks.StructBlock', [[('recipient_list', 0), ('from_email', 1), ('reply_to', 2), ('subject', 3), ('message', 4)]], {})}, default=[{'type': 'email_to_send', 'value': {'message': 'Hello {author.full_name},</p><p>On {result.publish_date} at {result.publish_time}, the user {user.full_name} has submitted the form "{form.title}", with the following content:</p><p></p><p>{result.data}</p><p></p><p>Have a nice day.', 'recipient_list': '{author.email}', 'subject': 'New entry for form "{form.title}"'}}, {'type': 'email_to_send', 'value': {'message': 'Hello {user.full_name},</p><p>You just submitted the form "{form.title}", with the following content:</p><p></p><p>{result.data}</p><p></p><p>The form author has been informed.</p><p>Have a nice day.', 'recipient_list': '{user.email}', 'subject': 'Confirmation of the submission of the form "{form.title}"'}}], verbose_name='E-mails to send after form submission')),
                ('administrators', modelcluster.fields.ParentalManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='administrators')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.contrib.forms.models.FormMixin, 'wagtailcore.page'),
        ),
    ]
