# Generated by Django 5.1.4 on 2025-01-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_fileinput_formindexpage_formpage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customformsubmission',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
